package protocol

// NCMCreatePlaylistResponseData is the json struct of response data, performing a request that create a playlist
type NCMCreatePlaylistResponseData struct {
	ID       int64 `json:"id"`
	Code     int   `json:"code"`
	Playlist struct {
		Subscribers           []interface{} `json:"subscribers"`
		Subscribed            interface{}   `json:"subscribed"`
		Creator               interface{}   `json:"creator"`
		Artists               interface{}   `json:"artists"`
		Tracks                interface{}   `json:"tracks"`
		UpdateFrequency       interface{}   `json:"updateFrequency"`
		BackgroundCoverID     int           `json:"backgroundCoverId"`
		BackgroundCoverURL    interface{}   `json:"backgroundCoverUrl"`
		TitleImage            int           `json:"titleImage"`
		TitleImageURL         interface{}   `json:"titleImageUrl"`
		EnglishTitle          interface{}   `json:"englishTitle"`
		OpRecommend           bool          `json:"opRecommend"`
		RecommendInfo         interface{}   `json:"recommendInfo"`
		AdType                int           `json:"adType"`
		TrackNumberUpdateTime int           `json:"trackNumberUpdateTime"`
		SubscribedCount       int           `json:"subscribedCount"`
		CloudTrackCount       int           `json:"cloudTrackCount"`
		UserID                int           `json:"userId"`
		CreateTime            int64         `json:"createTime"`
		HighQuality           bool          `json:"highQuality"`
		CoverImgID            int64         `json:"coverImgId"`
		NewImported           bool          `json:"newImported"`
		Anonimous             bool          `json:"anonimous"`
		UpdateTime            int64         `json:"updateTime"`
		SpecialType           int           `json:"specialType"`
		CommentThreadID       string        `json:"commentThreadId"`
		CoverImgURL           string        `json:"coverImgUrl"`
		TotalDuration         int           `json:"totalDuration"`
		Privacy               int           `json:"privacy"`
		TrackUpdateTime       int           `json:"trackUpdateTime"`
		TrackCount            int           `json:"trackCount"`
		PlayCount             int           `json:"playCount"`
		Ordered               bool          `json:"ordered"`
		Tags                  []interface{} `json:"tags"`
		Description           interface{}   `json:"description"`
		Status                int           `json:"status"`
		Name                  string        `json:"name"`
		ID                    int64         `json:"id"`
	} `json:"playlist"`
}

// NCMPlaylistDetailResponseData is the json struct of response data, performing a request that create a playlist
type NCMPlaylistDetailResponseData struct {
	Code          int         `json:"code"`
	RelatedVideos interface{} `json:"relatedVideos"`
	Playlist      struct {
		Subscribers []struct {
			DefaultAvatar      bool        `json:"defaultAvatar"`
			Province           int         `json:"province"`
			AuthStatus         int         `json:"authStatus"`
			Followed           bool        `json:"followed"`
			AvatarURL          string      `json:"avatarUrl"`
			AccountStatus      int         `json:"accountStatus"`
			Gender             int         `json:"gender"`
			City               int         `json:"city"`
			Birthday           int64       `json:"birthday"`
			UserID             int         `json:"userId"`
			UserType           int         `json:"userType"`
			Nickname           string      `json:"nickname"`
			Signature          string      `json:"signature"`
			Description        string      `json:"description"`
			DetailDescription  string      `json:"detailDescription"`
			AvatarImgID        int64       `json:"avatarImgId"`
			BackgroundImgID    int64       `json:"backgroundImgId"`
			BackgroundURL      string      `json:"backgroundUrl"`
			Authority          int         `json:"authority"`
			Mutual             bool        `json:"mutual"`
			ExpertTags         interface{} `json:"expertTags"`
			Experts            interface{} `json:"experts"`
			DjStatus           int         `json:"djStatus"`
			VipType            int         `json:"vipType"`
			RemarkName         interface{} `json:"remarkName"`
			AvatarImgIDStr     string      `json:"avatarImgIdStr"`
			BackgroundImgIDStr string      `json:"backgroundImgIdStr"`
			AvatarImgIDStr2    string      `json:"avatarImgId_str"`
		} `json:"subscribers"`
		Subscribed bool `json:"subscribed"`
		Creator    struct {
			DefaultAvatar      bool        `json:"defaultAvatar"`
			Province           int         `json:"province"`
			AuthStatus         int         `json:"authStatus"`
			Followed           bool        `json:"followed"`
			AvatarURL          string      `json:"avatarUrl"`
			AccountStatus      int         `json:"accountStatus"`
			Gender             int         `json:"gender"`
			City               int         `json:"city"`
			Birthday           int64       `json:"birthday"`
			UserID             int         `json:"userId"`
			UserType           int         `json:"userType"`
			Nickname           string      `json:"nickname"`
			Signature          string      `json:"signature"`
			Description        string      `json:"description"`
			DetailDescription  string      `json:"detailDescription"`
			AvatarImgID        int64       `json:"avatarImgId"`
			BackgroundImgID    int64       `json:"backgroundImgId"`
			BackgroundURL      string      `json:"backgroundUrl"`
			Authority          int         `json:"authority"`
			Mutual             bool        `json:"mutual"`
			ExpertTags         interface{} `json:"expertTags"`
			Experts            interface{} `json:"experts"`
			DjStatus           int         `json:"djStatus"`
			VipType            int         `json:"vipType"`
			RemarkName         interface{} `json:"remarkName"`
			AvatarImgIDStr     string      `json:"avatarImgIdStr"`
			BackgroundImgIDStr string      `json:"backgroundImgIdStr"`
			AvatarImgIDStr2    string      `json:"avatarImgId_str"`
		} `json:"creator"`
		Tracks []struct {
			Name string `json:"name"`
			ID   int    `json:"id"`
			Pst  int    `json:"pst"`
			T    int    `json:"t"`
			Ar   []struct {
				ID    int           `json:"id"`
				Name  string        `json:"name"`
				Tns   []interface{} `json:"tns"`
				Alias []interface{} `json:"alias"`
			} `json:"ar"`
			Alia []interface{} `json:"alia"`
			Pop  int           `json:"pop"`
			St   int           `json:"st"`
			Rt   string        `json:"rt"`
			Fee  int           `json:"fee"`
			V    int           `json:"v"`
			Crbt interface{}   `json:"crbt"`
			Cf   string        `json:"cf"`
			Al   struct {
				ID     int           `json:"id"`
				Name   string        `json:"name"`
				PicURL string        `json:"picUrl"`
				Tns    []interface{} `json:"tns"`
				PicStr string        `json:"pic_str"`
				Pic    int64         `json:"pic"`
			} `json:"al"`
			Dt int `json:"dt"`
			H  struct {
				Br   int `json:"br"`
				Fid  int `json:"fid"`
				Size int `json:"size"`
				Vd   int `json:"vd"`
			} `json:"h"`
			M struct {
				Br   int `json:"br"`
				Fid  int `json:"fid"`
				Size int `json:"size"`
				Vd   int `json:"vd"`
			} `json:"m"`
			L struct {
				Br   int `json:"br"`
				Fid  int `json:"fid"`
				Size int `json:"size"`
				Vd   int `json:"vd"`
			} `json:"l"`
			A               interface{}   `json:"a"`
			Cd              string        `json:"cd"`
			No              int           `json:"no"`
			RtURL           interface{}   `json:"rtUrl"`
			Ftype           int           `json:"ftype"`
			RtUrls          []interface{} `json:"rtUrls"`
			DjID            int           `json:"djId"`
			Copyright       int           `json:"copyright"`
			SID             int           `json:"s_id"`
			Mark            int           `json:"mark"`
			OriginCoverType int           `json:"originCoverType"`
			NoCopyrightRcmd interface{}   `json:"noCopyrightRcmd"`
			Rtype           int           `json:"rtype"`
			Rurl            interface{}   `json:"rurl"`
			Mst             int           `json:"mst"`
			Cp              int           `json:"cp"`
			Mv              int           `json:"mv"`
			PublishTime     int64         `json:"publishTime"`
		} `json:"tracks"`
		TrackIds []struct {
			ID  int         `json:"id"`
			V   int         `json:"v"`
			At  int64       `json:"at"`
			Alg interface{} `json:"alg"`
		} `json:"trackIds"`
		UpdateFrequency       interface{} `json:"updateFrequency"`
		BackgroundCoverID     int         `json:"backgroundCoverId"`
		BackgroundCoverURL    interface{} `json:"backgroundCoverUrl"`
		TitleImage            int         `json:"titleImage"`
		TitleImageURL         interface{} `json:"titleImageUrl"`
		EnglishTitle          interface{} `json:"englishTitle"`
		OpRecommend           bool        `json:"opRecommend"`
		CoverImgID            int64       `json:"coverImgId"`
		UpdateTime            int64       `json:"updateTime"`
		TrackCount            int         `json:"trackCount"`
		CommentThreadID       string      `json:"commentThreadId"`
		TrackNumberUpdateTime int64       `json:"trackNumberUpdateTime"`
		Privacy               int         `json:"privacy"`
		TrackUpdateTime       int64       `json:"trackUpdateTime"`
		CreateTime            int64       `json:"createTime"`
		HighQuality           bool        `json:"highQuality"`
		PlayCount             int         `json:"playCount"`
		NewImported           bool        `json:"newImported"`
		CoverImgURL           string      `json:"coverImgUrl"`
		SpecialType           int         `json:"specialType"`
		Ordered               bool        `json:"ordered"`
		Description           string      `json:"description"`
		UserID                int         `json:"userId"`
		Tags                  []string    `json:"tags"`
		SubscribedCount       int         `json:"subscribedCount"`
		CloudTrackCount       int         `json:"cloudTrackCount"`
		AdType                int         `json:"adType"`
		Status                int         `json:"status"`
		Name                  string      `json:"name"`
		ID                    int         `json:"id"`
		ShareCount            int         `json:"shareCount"`
		CoverImgIDStr         string      `json:"coverImgId_str"`
		CommentCount          int         `json:"commentCount"`
	} `json:"playlist"`
	Urls       interface{} `json:"urls"`
	Privileges []struct {
		ID            int  `json:"id"`
		Fee           int  `json:"fee"`
		Payed         int  `json:"payed"`
		St            int  `json:"st"`
		Pl            int  `json:"pl"`
		Dl            int  `json:"dl"`
		Sp            int  `json:"sp"`
		Cp            int  `json:"cp"`
		Subp          int  `json:"subp"`
		Cs            bool `json:"cs"`
		Maxbr         int  `json:"maxbr"`
		Fl            int  `json:"fl"`
		Toast         bool `json:"toast"`
		Flag          int  `json:"flag"`
		PreSell       bool `json:"preSell"`
		PlayMaxbr     int  `json:"playMaxbr"`
		DownloadMaxbr int  `json:"downloadMaxbr"`
	} `json:"privileges"`
}
